# Changes here will be overwritten by Copier.
_commit: 598247d
_src_path: gh:Bullish-Design/templateer
author_email: BullishDesignLLC@gmail.com
author_fullname: Bullish Design
author_username: Bullish-Design
copyright_date: '2025'
copyright_holder: Bullish Design
copyright_holder_email: BullishDesignLLC@gmail.com
copyright_license: ISC
insiders: false
project_description: 'A Github manager - Provides objects and syncs the github api
    with your local state, with a goal of allowing you finer control/integration of
    your discussions, projects, and issues.  '
project_name: Gitman
python_package_command_line_name: gitman
python_package_distribution_name: gitman
python_package_import_name: gitman
repository_name: gitman
repository_namespace: Bullish-Design
repository_provider: github.com

